import { Classifiers } from "../types/classifiers";

export const classifiers: Classifiers = {
    age: { options: [] },
    agriculturalLandType: {
        options: [
            {
                isMainType: true,
                isCountable: false,
                id: 1,
                code: "AUGKOPIBA",
                activeFrom: "2020-10-14T00:00:00",
                description: { lv: "Augkopība", en: "Cropping", ru: "Растениеводство" },
            },
            {
                isMainType: true,
                isCountable: true,
                id: 2,
                code: "LOPKOPIBA",
                activeFrom: "2020-10-14T00:00:00",
                description: { lv: "Lopkopība", en: "Livestock", ru: "Животноводство" },
            },
            {
                isMainType: false,
                isCountable: true,
                id: 3,
                code: "BISKOPIBA",
                activeFrom: "2020-10-14T00:00:00",
                description: { lv: "Biškopība", en: "Beekeeping", ru: "Пчеловодство" },
            },
            {
                isMainType: false,
                isCountable: true,
                id: 4,
                code: "PUTNKOPIBA",
                activeFrom: "2020-10-14T00:00:00",
                description: { lv: "Putnkopība", en: "Poultry", ru: "Птицеводство" },
            },
            {
                id: 5,
                code: "CITS",
                activeFrom: "2020-10-14T00:00:00",
                description: { lv: "Cits", en: "Other", ru: "Другое" },
            },
        ],
    },
    species: { options: [] },
    damagedAreaType: { options: [] },
    damageType: { options: [] },
    damageVolumeType: { options: [] },
    deathType: { options: [] },
    signsOfDisease: { options: [] },
    forestDamageType: { options: [] },
    gender: { options: [] },
    huntedType: { options: [] },
    infrastructureType: { options: [] },
    observationType: { options: [] },
    observedSigns: { options: [] },
    treeSpecies: { options: [] },
    dogBreeds: { options: [] },
    dogSubBreeds: { options: [] },
    huntersCardTypes: { options: [] },
    huntingSeasons: { options: [] },
    permitAllowances: { options: [] },
    permitTypes: { options: [] },
    strapStatuses: { options: [] },
    errorMessages: { options: [] },
};
